server:
  port: 8003
configuration:
  projectName: Spring Cloud
spring:
  boot:
    admin:
      client:
        url: http://localhost:8888/admin
management:
  endpoint:
    health:
      show-details: always
logging:
  pattern:
    console: "%d{ABSOLUTE} %-5p [%c{1}] [%t] [%m]%n"
  logback:
    rollingpolicy:
      max-history: 5
      max-file-size: 10MB
  file: 
    name: core.log
  
  
 