server:
  port: 8003
configuration:
  projectName: Spring Cloud2
spring:
  boot:
    admin:
      client:
        url: http://localhost:8888/admin
management:
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: core.log
logging:
  logback:
    rollingpolicy:
      max-history: 5
      max-file-size: 10MB
  file: 
    name: core.log
  
  
 