server:
  port: 8003
configuration:
  projectName: Spring Cloud
spring:
  boot:
    admin:
      client:
        url: http://localhost:8888/admin
management:
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: core.log
  logback:
    rollingpolicy:
      max-history: 5
      max-file-size: 10MB